---
- name: validate role spec
  validate_role_spec:
    spec: get_spec.yaml

- name: invoke network provider
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: config_manager/get
